### ISSUE TITLE
Can not paste text from clipboard 

### ISSUE THREAD

**Issue by przemkow** [miroslaw-bogacz/time-tracker#11]
User should be able to copy JIRA link and paste it as JIRA www address

**Actual result:**
Copy/Paste does not work

**Expected result:**
When user copy JIRA link he should be able to paste it in Time Tracker® form.

**Comment by przemkow** [comment]
@miroslaw-bogacz i've created PR with that improvement 
#13

**Comment by miroslaw-bogacz** [comment]
merged
